version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/drone_db
      OPENSKY_CLIENT_ID: your-client-id
      OPENSKY_CLIENT_SECRET: your-client-secret

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: drone_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
